services:
  bitwarden:
    image: vaultwarden/server:latest
    container_name: bitwarden
    restart: always
    environment:
      - WEBSOCKET_ENABLED=true
      - SIGNUPS_ALLOWED=${BITWARDEN_SIGNUPS_ALLOWED:-false}
      - DOMAIN=${BITWARDEN_DOMAIN}
      - SMTP_HOST=${MAIL_HOST}
      - SMTP_FROM=${MAIL_FROM}
      - SMTP_FROM_NAME=Vaultwarden
      - SMTP_USERNAME=${MAIL_USERNAME}
      - SMTP_PASSWORD=${MAIL_PASSWORD}
      - SMTP_SECURITY=${MAIL_SECURITY:-starttls}
      - SMTP_PORT=${MAIL_PORT}
    volumes:
      - ./bitwarden-data:/data
    ports:
      - "80:80"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  bitwarden-cf-tunnel:
    container_name: bitwarden-cf-tunnel
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token ${BITWARDEN_CF_TUNNEL_TOKEN}
    restart: unless-stopped
    network_mode: host
    profiles:
      - cloudflare
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_SCHEDULE=0 0 1 * * *  # Run daily at 1:00 AM
      - WATCHTOWER_NOTIFICATIONS=shoutrrr
      - "WATCHTOWER_NOTIFICATION_URL=smtp://${MAIL_USERNAME}:${MAIL_PASSWORD}@${MAIL_HOST}:${MAIL_PORT}/?from=${MAIL_FROM}&to=${MAIL_TO}"

  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Manila
      - CLI_ARGS= #optional
    volumes:
      - ./duplicati/config:/config
      - ./duplicati/backups:/backups
      - ./:/source
    ports:
      - 8200:8200
    restart: unless-stopped

  portainer_agent:
    image: portainer/agent:latest
    container_name: portainer_agent
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    ports:
      - "9001:9001"
